/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:66d5ce93-1785-4ee9-9345-e0bdb13d7e38",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ixGtGR7AB",
    "aws_user_pools_web_client_id": "3r9mhp7a4j34p9vkh3fqqaisrf",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://wcr7lajocje2tnk7f2c27g3h3i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "contacts78b48b0ca76c4f4eb72a6cdb8b85cb5793958-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
